version: '2'
services:
  fluentd:
    image: substratus/fluentd
    build: fluentd
    restart: always
    volumes:
      - ./fluentd/etc:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluent.conf
    container_name: fluentd
    hostname: fluentd
    network_mode: "host"
    # ports:
    #   - 24284
    ## exposes 24284
  elasticsearch:
    image: substratus/elasticsearch:20160526
    build: elasticsearch
    restart: always
    # ports:
    #   - 9200:9200
    network_mode: "host"
    ## exposes 9200 9300
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - INDEX_NAME=development
  kibana:
    image: substratus/kibana:20160526
    build: kibana
    restart: always
    network_mode: "host"
    # ports:
    #   - 5601:80
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    container_name: kibana
